package Multithreading;

public class MultithreadingNewRunnable {

  public static void main(String[] args) {
    /*
     * Creating an instance of Runnable through functional interface.
     * Starting a thread having this runnable instance.
     * Initially t.getState() will print NEW and once t.start() has run, then it most likely prints RUNNABLE.
     * t.getName() will print Thread-0, because the thread is not named explicitly, so it takes autogenerated name,
     * which follows this naming convention: Thread-<int for thread number>
     * Thread.currentThread().getName() return "main" as that is the running thread in this case.
     */
    Runnable runnable = () -> System.out.println("Lambda expression for instantiating Runnable");
    Thread t = new Thread(runnable);
    System.out.println(t.getState());
    t.start();
    System.out.println(t.getState());
    System.out.println(t.getName());
    System.out.println(Thread.currentThread().getName());
  }
}
